### ISSUE TITLE
GOF Unused Argument

### ISSUE THREAD

**Issue by kmcnayr** [matthewjdenny/GERGM#2]
I installed GERGM v0.10.5 from GitHub following the instructions in the Getting Started vignette. When running through the guide I am receiving the error, "Error in calculate_additional_GOF_statistics(GERGM_Object, modularity_group_memberships,  :   unused argument (observed_support = observed_support)" when running the GOF(test).

My specs:
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          3.2                         
year           2016                        
month          10                          
day            31                          
svn rev        71607                       
language       R                           
version.string R version 3.3.2 (2016-10-31)
nickname       Sincere Pumpkin Patch

Please let me know if I've missed something and this is not actually an issue.

**Comment by kmcnayr** [comment]
I am also getting the same error in Windows using R version 3.2.2

platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          2.2                         
year           2015                        
month          08                          
day            14                          
svn rev        69053                       
language       R                           
version.string R version 3.2.2 (2015-08-14)
nickname       Fire Safety

**Comment by matthewjdenny** [comment]
Thanks for pointing this out, I am working to figure it out and will get back to you. This is just likely an issue with the documentation or the default argument in one of the functions, should have a fix by tomorrow!

**Comment by matthewjdenny** [comment]
Issue should be fixed, that was a deprecated argument that should have been removed from the internal function.

**Comment by kmcnayr** [comment]
I can confirm it is fixed in the master branch. Thanks!
